[package]
name = "aster-chess"
version = "0.0.0"
edition = "2021"
description = "Simple chess game"
repository = "https://github.com/asterful/chess/"
authors = ["Aster Posso"]
readme = "README.md"
keywords = ["gamedev", "chess"]


[dependencies]
